name: Create release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo tag name
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "${{ steps.release.outputs.tag_name }}"
          echo "RELEASE_CREATED=${{ steps.release.outputs.release_created }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ steps.release.outputs.release_created }}" >> $GITHUB_ENV

  build-alacrity:
    needs: create-release

    if: $RELEASE_CREATED

    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Echo tag name
        run: echo "$RELEASE_CREATED"
