name: Create release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
