name: Create release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo tag name
        if: ${{ steps.release.outputs.release_created }}
        run: echo "${{ steps.release.outputs.tag_name }}"
