name: Create release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}

  build-alacrity:
    needs: create-release

    if: ${{ needs.create-release.outputs.release-created }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Echo tag name
        run: echo "Build Alacrity ${{ needs.create-release.outputs.tag-name }} for platform ${{ matrix.platform }}."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies(Ubuntu only)
        if: matrix.platform == "ubuntu-20.04"
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install frontend dependencies
        run: yarn install

      - name: Build Alacrity
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
